import DeterminateRandom from './lib/determinate_random.js'
import constants from './lib/constants.js';
import { makeHorizontalDivider, makeVerticalDivider } from './lib/dividers/general_divider.js';
import divide from './lib/divide.js';

import SolidColor from './lib/fillers/solid_color.js';
import PerlinNoise from './lib/fillers/perlin.js';
import Gradient from './lib/fillers/gradient.js';
import Hatching from './lib/fillers/hatching.js';
import Concentric from './lib/fillers/concentric.js';
import Marker from './lib/fillers/marker.js';
import Waves from './lib/fillers/waves.js';
import Mosaic from './lib/fillers/mosaic.js';
import Splatter from './lib/fillers/splatter.js';

import colors from './lib/colors.js';

const canvasSize = 2048;

const rand = new DeterminateRandom(Math.random() * 1000);

// this variable controls the position of divided divisions
// if true, the first division always starts at x or y = 0
// instead of the original divisions x or y coordinate
const leftTopBias = true;

const phiFract = 1 / constants.phi;

const fractions = [
    {
        data: [ phiFract, 1 - phiFract ],
        name: 'phi left'
    },
    {
        data:[ 1 - phiFract, phiFract ],
        name: 'phi right'
    },
    {
        data: [ 0.5, 0.5 ],
        name: 'halves'
    },
    {
        data:[ 1/3, 1/3, 1/3 ],
        name: 'thirds'
    },
    {
        data: [ .25, .25, .25, .25 ],
        name: 'quarters'
    }
];

const dividers = [
    ...fractions.map(f => ({ name: `${f.name} horizontal`, fn: makeHorizontalDivider(f.data) })),
    ...fractions.map(f => ({ name: `${f.name} vertical`, fn: makeVerticalDivider(f.data) }))
];

const divisions = divide({
    dividers,
    steps: 4,
    rand,
    leftTopBias
});

let selectedDivisions = [];
const selectionFraction = 0.03;


for ( let i = 0 ; i < divisions.length * selectionFraction ; i += 1 ) {

    const randomIndex = rand.random_int(0,divisions.length - 1);

    selectedDivisions = [ 
        ...selectedDivisions,
        divisions[randomIndex]
    ];
}

selectedDivisions.sort((a,b) => b.area - a.area);

//console.log(divisions);
//console.log(selectedDivisions)

const colorScheme = colors[ rand.random_int(0,colors.length - 1) ];

const solidColor = new SolidColor('rgba(0,0,0,0.1)');
const perlin = new PerlinNoise();
const gradient = new Gradient();
const hatching = new Hatching(6, 1.5);
const concentric = new Concentric(12, 'circle');
const marker = new Marker(2, 0.4);
const waves = new Waves(15, 0.03, 8);
const mosaic = new Mosaic(20, 2, 0.3);
const splatter = new Splatter(500, 15);

const fillers = [
    // solidColor,
    perlin,
    gradient,
    // hatching,
    // concentric,
    marker,
    // waves,
    // mosaic,
    // splatter

];

console.log(fillers)

const randomFiller = fillers => fillers[ rand.random_int(0,fillers.length - 1) ]
console.log(randomFiller(fillers))
const numberOfFillers = Math.random() > 0.9 ? 3 : 2;
const selectedFillers = [
    ...Array.from({ length: numberOfFillers }, () => randomFiller(fillers)),
    ...(Array(20).fill(solidColor))    
];

console.log(selectedFillers);

const canvas = document.createElement('CANVAS');
canvas.width = canvasSize;
canvas.height = canvasSize;

// Fill with white background
const ctx = canvas.getContext('2d');
ctx.fillStyle = '#ffffff';
ctx.fillRect(0, 0, canvasSize, canvasSize);

// Scale divisions to 90% with 5% border on each side
const padding = 0.05;
const scale = 0.9;

// Draw all divisions onto the same canvas
for ( let division of selectedDivisions ) {
    const color = colorScheme.set.main[ rand.random_int(0, colorScheme.set.main.length - 1) ];
    // Transform division coordinates to fit within padded area
    const scaledDivision = {
        ...division,
        left: padding + division.left * scale,
        top: padding + division.top * scale,
        width: division.width * scale,
        height: division.height * scale
    };
    selectedFillers[ rand.random_int(0,selectedFillers.length - 1) ].draw({ canvas, division: scaledDivision, color });
}

// Add signature text in lower right corner
ctx.font = `${Math.floor(canvasSize * 0.015)}px 'Trebuchet MS', sans-serif`;
ctx.fillStyle = 'rgba(230, 230, 230, 0.15)';
ctx.textAlign = 'right';
ctx.textBaseline = 'bottom';
ctx.fillText('Generated by kevinkleine.com', canvasSize * 0.98, canvasSize * 0.99);

const holder = document.getElementsByTagName('div')[0];
holder.appendChild(canvas);

const resizeHolder = function() {
    const minAxis = Math.min( canvasSize, window.innerWidth - 40, window.innerHeight - 40 );
    holder.style.width = minAxis + 'px';
    holder.style.height = minAxis + 'px';
}

resizeHolder();

window.addEventListener('resize', resizeHolder);
document.addEventListener('click', () => location.reload());
